#!/usr/bin/env python3
"""Generates rp/src/game_table.c: the game's logic as data (game_table.h).

From DirkSimple's game.lua (third_party/dirksimple, zlib licence, Ryan C.
Gordon), read with tools/game/game_to_json.lua (needs `lua`), and the SNES
project's laserdisc segment table (third_party/snes-superdragonslairarcade,
MIT licence, Chad Doebelin), each sequence placed in a CD clip by
tools/game/clipmap.py with the clips' lengths in tools/game/clip_frames.json.

  python3 tools/game/gen_game_table.py [OUT]
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import clipmap  # noqa: E402

INPUTS = ["up", "down", "left", "right", "upleft", "upright", "downleft",
          "downright", "action", "start"]
INTERRUPTS = {None: "GAME_INT_NONE", "start_game": "GAME_INT_START_GAME",
              "game_over_complete": "GAME_INT_GAME_OVER_COMPLETE"}


def ms(value):
    v = int(round(value or 0))
    assert 0 <= v <= 0xFFFF, value
    return v


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "rp", "src", "game_table.c")
    game_lua = os.path.join(ROOT, "third_party", "dirksimple", "game.lua")
    game = json.loads(subprocess.check_output(
        ["lua", os.path.join(HERE, "game_to_json.lua"), game_lua]))
    with open(os.path.join(ROOT, "third_party", "snes-superdragonslairarcade", "segment_timing.json")) as f:
        segments = json.load(f)["segments"]
    frames = clipmap.clip_frames(os.path.join(HERE, "clip_frames.json"))
    _, placed, missing = clipmap.build(game, segments, frames)
    not_on_cd = {(scene, seq) for scene, seq, _ in missing}

    clips = sorted(frames)
    clip_index = {c: i for i, c in enumerate(clips)}
    assert len(clips) < 0xFF

    scenes = sorted(game["scenes"])
    seq_index = {}
    order = []
    for scene in scenes:
        for seq in sorted(game["scenes"][scene]):
            seq_index[(scene, seq)] = len(order)
            order.append((scene, seq))

    def next_of(scene, name):
        if name is None:
            return "GAME_SEQ_NONE"
        return str(seq_index[(scene, name)])

    lines = []
    w = lines.append
    w("/* Generated by tools/game/gen_game_table.py: do not edit.")
    w(" *")
    w(" * Dragon's Lair's logic, from DirkSimple's game.lua")
    w(" * (https://github.com/icculus/DirkSimple, zlib licence, Ryan C. Gordon),")
    w(" * each sequence placed in a CD clip through the SNES project's laserdisc")
    w(" * segment table (https://github.com/astrobleem/SNES-SuperDragonsLairArcade,")
    w(" * MIT licence, Chad Doebelin). See game_table.h. */")
    w("")
    w('#include "game_table.h"')
    w("")
    w("#include <stddef.h>")
    w("")
    w("const game_clip_t game_clips[] = {")
    for c in clips:
        w("    {%s, %d}," % (c_string(c), frames[c]))
    w("};")
    w("const uint16_t game_clip_count = %d;" % len(clips))
    w("")

    actions = []
    w("const game_sequence_t game_sequences[] = {")
    for scene, seq in order:
        d = game["scenes"][scene][seq]
        p = placed.get((scene, seq))
        flags = []
        if d.get("kills_player"):
            flags.append("GAME_SEQ_KILLS")
        if d.get("is_single_frame"):
            flags.append("GAME_SEQ_SINGLE_FRAME")
        if (scene, seq) in not_on_cd:
            flags.append("GAME_SEQ_NOT_ON_CD")
        to = d.get("timeout") or {}
        first = len(actions)
        for a in d.get("actions") or []:
            actions.append((a, scene))
        clip = str(clip_index[p["clip"]]) if p else "GAME_CLIP_NONE"
        then = str(clip_index[p["then"]]) if p and p["then"] else "GAME_CLIP_NONE"
        w("    {%s, %s, %d, %s, %s, %d, %s, %d, %d, %d},  // %s.%s" % (
            clip, then, p["frame"] if p else 0, " | ".join(flags) or "0",
            INTERRUPTS[to.get("interrupt")], ms(to.get("when")),
            next_of(scene, to.get("nextsequence")), to.get("points") or 0,
            first, len(actions) - first, scene, seq))
    w("};")
    w("const uint16_t game_sequence_count = %d;" % len(order))
    w("")
    w("const char *const game_sequence_names[] = {")
    for scene, seq in order:
        w("    %s," % c_string(seq))
    w("};")
    w("")
    w("const game_action_t game_actions[] = {")
    for a, scene in actions:
        w("    {GAME_IN_%s, %s, %d, %d, %s, %d}," % (
            a["input"].upper(), INTERRUPTS[a.get("interrupt")], ms(a["from"]),
            ms(a["to"]), next_of(scene, a.get("nextsequence")), a.get("points") or 0))
    w("};")
    w("const uint16_t game_action_count = %d;" % len(actions))
    w("")
    w("const game_scene_t game_scenes[] = {")
    for scene in scenes:
        seqs = sorted(game["scenes"][scene])
        first = seq_index[(scene, seqs[0])]

        def entry(name):
            return str(seq_index[(scene, name)]) if name in game["scenes"][scene] else "GAME_SEQ_NONE"
        w("    {%s, %s, %d, %d, %s, %s, %s}," % (
            c_string(scene), c_string(scene.replace("_", " ").upper()), first, len(seqs),
            entry("start_alive"), entry("start_dead"), entry("game_over")))
    w("};")
    w("const uint16_t game_scene_count = %d;" % len(scenes))
    w("")
    w("const uint8_t game_rows[][GAME_ROW_SCENES] = {")
    for row in game["rows"]:
        w("    {%s}," % ", ".join(str(scenes.index(s)) for s in row))
    w("};")
    w("const uint16_t game_row_count = %d;" % len(game["rows"]))
    w("const uint16_t game_attract_scene = %d;" % scenes.index("attract_mode"))
    w("const uint16_t game_intro_scene = %d;" % scenes.index("introduction"))
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("%s: %d clips, %d scenes, %d sequences (%d placed, %d not on the CD), %d actions, %d rows" % (
        out_path, len(clips), len(scenes), len(order), len(placed), len(missing), len(actions),
        len(game["rows"])))


if __name__ == "__main__":
    main()
