/**
 * File: game_table.h
 * Description: The game's logic as data: Dragon's Lair's scenes, their
 *              sequences, the moves (an input in a time window, and where
 *              it leads) and the order of the scenes, each sequence placed
 *              in a clip of the CD-ROM at a frame of its clip file.
 *
 * game_table.c is generated by tools/game/gen_game_table.py from
 * DirkSimple's game.lua (https://github.com/icculus/DirkSimple, zlib
 * licence, Ryan C. Gordon) and the SNES project's laserdisc segment table
 * (https://github.com/astrobleem/SNES-SuperDragonsLairArcade, MIT licence,
 * Chad Doebelin), both in third_party/. Times are in milliseconds from the
 * sequence's start, as DirkSimple counts them.
 */

#ifndef GAME_TABLE_H
#define GAME_TABLE_H

#include <stdint.h>

// What a move asks for: a direction (a stick's eight, or the arrow keys),
// the sword (fire, space), or start.
enum {
  GAME_IN_UP = 0,
  GAME_IN_DOWN,
  GAME_IN_LEFT,
  GAME_IN_RIGHT,
  GAME_IN_UPLEFT,
  GAME_IN_UPRIGHT,
  GAME_IN_DOWNLEFT,
  GAME_IN_DOWNRIGHT,
  GAME_IN_ACTION,
  GAME_IN_START,
  GAME_INPUTS
};

// What a move or a timeout does beside going to a sequence.
enum {
  GAME_INT_NONE = 0,
  GAME_INT_START_GAME,          // the attract mode's start
  GAME_INT_GAME_OVER_COMPLETE,  // a game over clip ended
};

#define GAME_SEQ_NONE 0xFFFFu  // no next sequence: the scene ends
#define GAME_CLIP_NONE 0xFFu   // no clip: the sequence plays on (no seek)

// Sequence flags.
#define GAME_SEQ_KILLS 0x01u         // Dirk dies in it
#define GAME_SEQ_SINGLE_FRAME 0x02u  // one picture held for its time
#define GAME_SEQ_NOT_ON_CD 0x04u     // seeks to frames the CD does not have

typedef struct {
  uint8_t input;      // GAME_IN_*
  uint8_t interrupt;  // GAME_INT_*
  uint16_t from_ms;   // the window, from the sequence's start
  uint16_t to_ms;
  uint16_t next;      // the sequence it leads to, or GAME_SEQ_NONE
  uint16_t points;
} game_action_t;

typedef struct {
  uint8_t clip;        // game_clips' index, or GAME_CLIP_NONE (plays on)
  uint8_t then_clip;   // the clip it plays on into, or GAME_CLIP_NONE
  uint16_t frame;      // its start in the clip, 25 frames a second
  uint8_t flags;       // GAME_SEQ_*
  uint8_t timeout_interrupt;  // GAME_INT_*
  uint16_t timeout_ms;
  uint16_t timeout_next;      // or GAME_SEQ_NONE: the scene ends
  uint16_t timeout_points;
  uint16_t first_action;      // game_actions' index
  uint16_t action_count;
} game_sequence_t;

typedef struct {
  const char *name;          // DirkSimple's ("flaming_ropes")
  const char *title;         // to show ("FLAMING ROPES")
  uint16_t first_sequence;   // game_sequences' index
  uint16_t sequence_count;
  uint16_t start_alive;      // the scene's entry sequences, or GAME_SEQ_NONE
  uint16_t start_dead;
  uint16_t game_over;
} game_scene_t;

typedef struct {
  char name[8];          // the clip file's name without ".DLC" ("S05D2")
  uint16_t frames;       // at 25 a second
  uint16_t first_start;  // game_starts' index of its sequences' starts
  uint16_t start_count;
} game_clip_t;

#define GAME_ROW_SCENES 3

extern const game_scene_t game_scenes[];
extern const uint16_t game_scene_count;
extern const game_sequence_t game_sequences[];
extern const char *const game_sequence_names[];
extern const uint16_t game_sequence_count;
extern const game_action_t game_actions[];
extern const uint16_t game_action_count;
extern const game_clip_t game_clips[];
extern const uint16_t game_clip_count;
// Every clip's sequence starts, ascending, by clip: the frames the
// converter lists as key pictures so that the game starts any at once.
extern const uint16_t game_starts[];
extern const uint16_t game_start_count;

// The clip named `name` (the clip file's or its source's, "S05D2" or
// "S05D2.MPG"), or -1.
int game_clip_find(const char *name);
extern const uint8_t game_rows[][GAME_ROW_SCENES];  // scene indices
extern const uint16_t game_row_count;
extern const uint16_t game_attract_scene;  // the attract mode's scene
extern const uint16_t game_intro_scene;    // the introduction's

#endif  // GAME_TABLE_H
