#!/usr/bin/env python3
"""Generates rp/src/include/scaler_tables.h: Lanczos-3 resampling weights
for picture16's downscale of the game's clips (352x240, chroma 176x120) to
the ST's low resolution (320x200, chroma 160x100).

The weights are computed here, in floating point, once; the firmware and the
PC tools use the same integers, so they scale to the same bytes. As ffmpeg's
`scale=...:flags=lanczos` (a = 3), the kernel is stretched by the reduction
factor (an anti-aliasing low-pass), the taps that fall outside the picture
are folded onto its edge pixel, and the weights of an output pixel sum to
exactly 1 << SCALER_SHIFT.

    python3 tools/gen_scaler_tables.py > rp/src/include/scaler_tables.h
"""

import math

TAPS = 8  # the most an axis needs (down: 240 -> 200 spans 8 lines)
SHIFT = 14
A = 3
X_PERIOD = 10  # across, 352 -> 320 and 176 -> 160: 10 outputs per 11 pixels
X_PERIOD_SRC = 11

# (name, source size, output size, taps the axis reads: across, 352 -> 320
# spans at most 7 pixels; down, 240 -> 200 spans 8 lines)
AXES = [
    ("luma_x", 352, 320, 7),
    ("luma_y", 240, 200, 8),
    ("chroma_x", 176, 160, 7),
    ("chroma_y", 120, 100, 8),
]


def lanczos(x):
    if x == 0:
        return 1.0
    if abs(x) >= A:
        return 0.0
    px = math.pi * x
    return A * math.sin(px) * math.sin(px / A) / (px * px)


def axis_weights(src, out, taps_read):
    scale = src / out
    support = A * scale
    rows = []
    for o in range(out):
        centre = (o + 0.5) * scale - 0.5
        first = math.floor(centre - support) + 1
        taps = {}
        for i in range(first, first + int(math.ceil(2 * support)) + 1):
            w = lanczos((i - centre) / scale)
            if w == 0.0:
                continue
            j = min(max(i, 0), src - 1)  # fold onto the edge
            taps[j] = taps.get(j, 0.0) + w
        lo = min(taps)
        hi = max(taps)
        assert hi - lo < taps_read, (src, out, o, hi - lo)
        # All the pixels read must lie in the line, zero weights included.
        lo = min(lo, src - taps_read)
        total = sum(taps.values())
        ints = [0] * TAPS
        for j, w in taps.items():
            ints[j - lo] = round(w / total * (1 << SHIFT))
        # Rounding: the weights must sum to exactly 1 << SHIFT.
        k = max(range(TAPS), key=lambda t: ints[t])
        ints[k] += (1 << SHIFT) - sum(ints)
        rows.append((lo, ints))
    return rows


def periodic_range(rows, period, period_src):
    """The outputs [lo, hi) whose weights repeat every `period` outputs, the
    first pixel advancing `period_src` (all but a few at each edge, where
    taps fold). Checked: every output there is its phase's, shifted."""
    out = len(rows)
    odd = [o for o in range(out - period)
           if rows[o + period][0] - rows[o][0] != period_src
           or rows[o + period][1] != rows[o][1]]
    lo = max([o + 1 for o in odd if o < out // 2], default=0)
    hi = min([o + period for o in odd if o >= out // 2], default=out)
    for o in range(lo, hi):
        base = lo + (o - lo) % period
        shift = (o - lo) // period * period_src
        assert rows[o][0] == rows[base][0] + shift, (o, base)
        assert rows[o][1] == rows[base][1], (o, base)
    assert hi - lo >= period
    return lo, hi


def main():
    print("// Generated by tools/gen_scaler_tables.py: do not edit.")
    print("//")
    print("// Lanczos-3 weights for 352x240 -> 320x200 (chroma 176x120 ->")
    print("// 160x100). For output pixel o of an axis: the first source pixel")
    print("// it reads, and SCALER_TAPS weights for it and the pixels after,")
    print("// summing to 1 << SCALER_SHIFT. Include from picture16.c only.")
    print("")
    print("#ifndef SCALER_TABLES_H")
    print("#define SCALER_TABLES_H")
    print("")
    print("#include <stdint.h>")
    print("")
    print(f"#define SCALER_TAPS {TAPS}")
    print(f"#define SCALER_SHIFT {SHIFT}")
    print("#define SCALER_TAPS_X 7  // across: the 8th weight is always 0")
    print("#define SCALER_TAPS_Y 8")
    print("#define SCALER_SRC_W 352")
    print("#define SCALER_SRC_H 240")
    print("#define SCALER_OUT_W 320")
    print("#define SCALER_OUT_H 200")
    print("")
    print("// Across, the weights repeat every SCALER_X_PERIOD outputs, the first")
    print("// pixel SCALER_X_PERIOD_SRC further on, for the outputs [LO, HI) of")
    print("// a line: all but those at the edges, where taps fold.")
    print(f"#define SCALER_X_PERIOD {X_PERIOD}")
    print(f"#define SCALER_X_PERIOD_SRC {X_PERIOD_SRC}")
    for name, src, out, taps_read in AXES:
        if name.endswith("_x"):
            lo, hi = periodic_range(axis_weights(src, out, taps_read),
                                    X_PERIOD, X_PERIOD_SRC)
            print(f"#define SCALER_{name.upper()}_LO {lo}")
            print(f"#define SCALER_{name.upper()}_HI {hi}")
    print("")
    print("typedef struct {")
    print("  int16_t first;")
    print(f"  int16_t weight[{TAPS}];")
    print("} scaler_tap_t;")
    for name, src, out, taps_read in AXES:
        rows = axis_weights(src, out, taps_read)
        print("")
        print(f"static const scaler_tap_t scaler_{name}[{out}] = {{")
        for lo, ints in rows:
            ws = ", ".join(str(w) for w in ints)
            print(f"    {{{lo}, {{{ws}}}}},")
        print("};")
    print("")
    print("#endif  // SCALER_TABLES_H")


if __name__ == "__main__":
    main()
